version: '2'

services:
  postgres:
    image: postgres:9.6
    platform: linux/amd64
    volumes:
      - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust  # <- tu peux commenter/retirer si tu imposes la connexion par mdp

  elasticsearch:
    image: elasticsearch:5.6
    platform: linux/amd64
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
    # ...
    ports:
      - "9200:9200"
      - "9300:9300"
    # ...

  kibana:
    image: kibana:5.6
    platform: linux/amd64
    environment:
      ELASTICSEARCH_HOSTS: http://fabmanager-elasticsearch:9200
    # ...
    ports:
      - "5601:5601"

  redis:
    image: redis:6-alpine
    # redis:6-alpine existe souvent en version ARM, donc tu *n'es pas obligé* de mettre platform
    # platform: linux/amd64
    ports:
      - "6379:6379"
    # ...

  mailcatcher:
    image: sj26/mailcatcher
    platform: linux/amd64
    ports:
      - "1080:1080"
      - "1025:1025"
    # ...

# Si tu étais sur Linux et voulais un réseau statique interne, tu garderais ci-dessous:
# networks:
#   fabmanager:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
#           gateway: 172.18.0.1
